name: slides_test

services:
    revealjs:
        build:
            target: test
        ports:
            - "8009:8009"
        volumes:
            - ./revealjs:/app
            - revealjs_test_node_modules:/app/node_modules
        networks:
            - slides_test

volumes:
    revealjs_test_node_modules:

networks:
    slides_test: