name: Slides

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Infrastructure]
    types: completed
    branches:
      - dev
      - stage
      - main
  push:
    paths:
      - 'slides/**'
      - '.github/workflows/slides.yml'
      - 'scripts/run_slides_test.sh'
      - 'scripts/build_slides.sh'
      
env:
  REGISTRY: ghcr.io
  # COMMIT_SHA: ${{ github.event.after }}
  COMMIT_SHA: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run slidess test in Docker
        run: ./scripts/run_slides_test.sh

  check_for_infrastructure_change:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Check for infrastructure changes
        id: check_for_infrastructure_change
        # replace --exit-code with --quite for less output on console if necessary!
        run: |
          if git diff --exit-code HEAD^ HEAD -- infrastructure/ .github/workflows/infrastructure.yml; then
            echo "No infrastructure changes detected."
            echo "infrastructure_changed=FALSE" >> $GITHUB_OUTPUT
          else
            echo "Infrastructure changes detected."
            echo "infrastructure_changed=TRUE" >> $GITHUB_OUTPUT
          fi
          echo "=== Contents of $GITHUB_OUTPUT ==="
          cat $GITHUB_OUTPUT
    outputs:
      infrastructure_changed: ${{ steps.check_for_infrastructure_change.outputs.infrastructure_changed }}

  build:
    # only run if no infrastructure changes were detected, but do run, if the workflow was triggered by a workflow_run event (then the github.event.workflow_run.head_sha is not null)
    # TBD: split into multiline if statement:
    if: ${{((github.event.ref == 'refs/heads/main' || github.event.ref == 'refs/heads/stage' || github.event.ref == 'refs/heads/dev') && needs.check_for_infrastructure_change.outputs.infrastructure_changed == 'FALSE' ) || ( ( github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'stage' || github.event.workflow_run.head_branch == 'stage' ) && github.event.workflow_run.name == 'Infrastructure' && github.event.workflow_run.conclusion == 'success') }}
    needs: [test, check_for_infrastructure_change]
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }} 

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for production
        run: ./scripts/build_slides.sh

      - name: Show images
        run: docker image list

      - name: Tag and push with latest and commit hash
        run: |
          docker tag \
            ${{github.event.repository.name}}-slides:latest \
            ${{env.REGISTRY}}/${{github.repository}}-slides:latest
          docker tag \
            ${{github.event.repository.name}}-slides:latest \
            ${{env.REGISTRY}}/${{github.repository}}-slides:$COMMIT_SHA
          docker push \
            ${{env.REGISTRY}}/${{github.repository}}-slides:latest
          docker push \
            ${{env.REGISTRY}}/${{github.repository}}-slides:$COMMIT_SHA

  deploy:
    needs: build
    if: |
      ${{ ((github.event.ref == 'refs/heads/main' || github.event.ref == 'refs/heads/stage' || github.event.ref == 'refs/heads/dev') && needs.check_for_infrastructure_change.outputs.infrastructure_changed == 'FALSE' ) ||
          ((github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'stage' || github.event.workflow_run.head_branch == 'dev' ) && github.event.workflow_run.name == 'Infrastructure' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      packages: read
    environment: |
      ${{
        (( github.ref == 'refs/heads/dev' || github.event.workflow_run.head_branch == 'dev' )) && 'dev' ||
        (( github.ref == 'refs/heads/stage' || github.event.workflow_run.head_branch == 'stage' )) && 'stage' ||
        (( github.ref == 'refs/heads/main' || github.event.workflow_run.head_branch == 'main' )) && 'prod'
      }}
    steps:

      - name: Echo environment
        run: |
          echo "AZURE_CONTAINERAPP_SLIDES: ${{ vars.AZURE_CONTAINERAPP_SLIDES }}"
          echo "AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_GITHUBACTIONSMANAGEDIDENTITY_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: Set workspace
      #   run: |
      #     if [ ${{ github.ref }} == 'refs/heads/dev' || github.event.workflow_run.head_branch == 'dev' ]; then
      #       echo "WORKSPACE=dev" >> "$GITHUB_ENV"
      #     elif [ ${{ github.ref }} == 'refs/heads/stage' || github.event.workflow_run.head_branch == 'stage' ]; then
      #       echo "WORKSPACE=stage" >> "$GITHUB_ENV"
      #     elif [ ${{ github.ref }} == 'refs/heads/main' || github.event.workflow_run.head_branch == 'main' ]; then
      #       echo "WORKSPACE=prod" >> "$GITHUB_ENV"
      #     else
      #       echo "This branch does not support deployment"
      #       exit 1
      #     fi
      #     echo "WORKSPACE=${WORKSPACE}"

      - name: Deploy
        run: |
          az containerapp update \
            --name ${{ vars.AZURE_CONTAINERAPP_SLIDES }} \
            --resource-group ${{vars.AZURE_RESOURCE_GROUP}} \
            --image ${{env.REGISTRY}}/${{github.repository}}-slides:$COMMIT_SHA

      - name: Logout from Azure
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear


# name: tests

# on:
#   - push

# permissions:
#   contents: read

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: slides

#     strategy:
#       matrix:
#         node-version:
#           - 18
#           - 20

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{ matrix.node-version }}

#       - name: Install dependencies
#         run: npm install

#       - name: Build website
#         run: npm run build --if-present

#       - name: Run tests
#         run: npm test
#         env:
#           CI: true
